
NBA_TEAMS_SLUGS = [
    "boston-celtics",
    "brooklyn-nets",
    "new-york-knicks",
    "philadelphia-76ers",
    "toronto-raptors",
    "chicago-bulls",
    "cleveland-cavaliers",
    "detroit-pistons",
    "indiana-pacers",
    "milwaukee-bucks",
    "atlanta-hawks",
    "charlotte-hornets",
    "miami-heat",
    "orlando-magic",
    "washington-wizards",
    "denver-nuggets",
    "minnesota-timberwolves",
    "oklahoma-city-thunder",
    "portland-trail-blazers",
    "utah-jazz",
    "golden-state-warriors",
    "la-clippers",
    "los-angeles-lakers",
    "phoenix-suns",
    "sacramento-kings",
    "dallas-mavericks",
    "houston-rockets",
    "memphis-grizzlies",
    "new-orleans-pelicans",
    "san-antonio-spurs"
]

NBA_PLAYERS_NAME_OWNED = [
    "Julius Randle",
    "Joel Embiid",
    "Anthony Davis",
    "Jayson Tatum",
    "Lauri Markkanen",
    "Damian Lillard",
    "Domantas Sabonis",
    "Nikola Vučević",
    "Shai Gilgeous-Alexander",
    "Trae Young",
    "Ja Morant",
    "Jimmy Butler",
    "Paul George",
    "Jaren Jackson Jr.",
    "Klay Thompson",
    "Pascal Siakam",
    "De'Aaron Fox",
    "Scottie Barnes",
    "Stephen Curry",
    "Zion Williamson",
    "Kristaps Porzingis",
    "Dejounte Murray",
    "Nic Claxton",
    "Jamal Murray",
    "Jerami Grant",
    "Andrew Wiggins",
    "Jordan Poole",
    "Thomas Bryant",
    "Darius Garland",
    "Jrue Holiday",
    "OG Anunoby",
    "Jarrett Allen",
    "D'Angelo Russell",
    "Keldon Johnson",
    "Marcus Smart",
    "Ben Simmons",
    "Malcolm Brogdon",
    "Tyus Jones",
    "Landry Shamet",
    "Saddiq Bey",
    "Tobias Harris",
    "Al Horford",
    "Jalen Duren",
    "Jarred Vanderbilt",
    "Kentavious Caldwell-Pope",
    "Monte Morris",
    "Robert Williams III",
    "Bennedict Mathurin",
    "Ivica Zubac",
    "Rui Hachimura",
    "Torrey Craig",
    "Jeremiah Robinson-Earl",
    "Trey Lyles",
    "Caleb Martin",
    "Jaylen Nowell",
    "Jonathan Kuminga",
    "Doug McDermott",
    "Shake Milton",
    "Bol Bol",
    "Troy Brown Jr.",
    "Josh Green",
    "Mo Bamba",
    "Joe Harris",
    "Oshae Brissett",
    "George Hill",
    "Kendrick Nunn",
    "Thaddeus Young",
    "Devonte' Graham",
    "Dewayne Dedmon",
    "Montrezl Harrell",
    "Terence Davis",
    "Jericho Sims",
    "Paul Reed",
    "Raul Neto",
    "DeAndre Jordan",
    "Payton Pritchard",
    "Max Christie",
    "Anthony Gill",
    "Udoka Azubuike",
    "Grayson Allen",
    "Buddy Hield",
    "Evan Mobley",
    "Keegan Murray",
    "Drew Eubanks",
    "Onyeka Okongwu"
]
